# Generated by Django 4.2 on 2023-05-13 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(db_column='stock', max_length=10)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('market_cap', models.CharField(db_column='market_cap', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data de Investimento')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Unitário')),
                ('amount', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('brokerage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Corretagem')),
                ('type', models.CharField(blank=True, choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1, verbose_name='Tipo')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
