# Generated by Django 4.2 on 2023-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='brokerage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Corretagem'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='code',
            field=models.CharField(max_length=200, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='taxab3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa B3'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Unitário'),
        ),
    ]
