# Generated by Django 3.2.18 on 2023-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_investment_subtotal_alter_investment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='type',
            field=models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], default='C', max_length=1),
        ),
    ]
