# Generated by Django 4.2 on 2023-05-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_investment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='taxab3',
        ),
    ]
