# Generated by Django 4.2 on 2023-05-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_investor_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='perfil',
            field=models.CharField(blank=True, choices=[('c', 'CONSERVADOR'), ('m', 'MODERADOR'), ('a', 'ASSERTIVO')], default='', max_length=20, null=True),
        ),
    ]
